package br.com.lojaveiculo.view;

import br.com.lojaveiculo.abstractview.TelaBaseCadastroView;
import java.awt.event.ActionListener;

/**
 *
 * @author eduar
 */
public final class CadastroVendaView extends TelaBaseCadastroView {

    public CadastroVendaView() {
        organizaLayout();
    }

    @Override
    public void organizaLayout() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(500, 600);
    }
   

    public void adicionaAcaoAoBtnSelecionarVeiculo(ActionListener acao) {
        btnSelecionaVeiculo.addActionListener(acao);
    }

    public void adicionaAcaoAoBtnSelecionarCliente(ActionListener acao) {
        btnSelecionaCliente.addActionListener(acao);
    }

    public void adicionaAcaoAoBtnSelecionarVendedor(ActionListener acao) {
        btnSelecionaVendedor.addActionListener(acao);
    }

    public void adicionaAcaoAoBtnEfetuarVenda(ActionListener acao) {
        btnEfetuarVenda.addActionListener(acao);
    }

    public void adicionaAcaoAoBtnCancelarVenda(ActionListener acao) {
        btnCancelarVenda.addActionListener(acao);
    }

    public void populaListaVeiculo(String veiculo) {
        txtaVeiculoSelecionado.append(veiculo);
    }

    public void populaListaVendedor(String vendedor) {
        txtaVendedorSelecionado.append(vendedor);
    }

    public void populaListaCliente(String cliente) {
        txtaClienteSelecionado.append(cliente);
    }
    
    public int getTipoVeiculo(){
        return cbTipoVeiculo.getSelectedIndex();
    }
    
    public void limparCampos(){
        txtaClienteSelecionado.setText("");
        txtaVendedorSelecionado.setText("");
        txtaVeiculoSelecionado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSelecionaVeiculo = new javax.swing.JButton();
        btnEfetuarVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaVeiculoSelecionado = new javax.swing.JTextArea();
        btnSelecionaVendedor = new javax.swing.JButton();
        lblVenderVeiculo = new javax.swing.JLabel();
        btnSelecionaCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaClienteSelecionado = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaVendedorSelecionado = new javax.swing.JTextArea();
        cbTipoVeiculo = new javax.swing.JComboBox<>();
        btnCancelarVenda = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Carro");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSelecionaVeiculo.setText("Selecionar Veículo");

        btnEfetuarVenda.setBackground(new java.awt.Color(0, 153, 102));
        btnEfetuarVenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEfetuarVenda.setForeground(new java.awt.Color(255, 255, 255));
        btnEfetuarVenda.setText("Efetuar Venda");

        txtaVeiculoSelecionado.setEditable(false);
        txtaVeiculoSelecionado.setColumns(20);
        txtaVeiculoSelecionado.setRows(5);
        jScrollPane1.setViewportView(txtaVeiculoSelecionado);

        btnSelecionaVendedor.setText("Selecionar Vendedor");

        lblVenderVeiculo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblVenderVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblVenderVeiculo.setText("Vender Veiculo");

        btnSelecionaCliente.setText("Selecionar Cliente");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtaClienteSelecionado.setEditable(false);
        txtaClienteSelecionado.setColumns(20);
        txtaClienteSelecionado.setRows(5);
        jScrollPane2.setViewportView(txtaClienteSelecionado);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtaVendedorSelecionado.setEditable(false);
        txtaVendedorSelecionado.setColumns(20);
        txtaVendedorSelecionado.setRows(5);
        txtaVendedorSelecionado.setPreferredSize(new java.awt.Dimension(150, 84));
        jScrollPane3.setViewportView(txtaVendedorSelecionado);

        cbTipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));

        btnCancelarVenda.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelarVenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarVenda.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarVenda.setText("Cancelar Venda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSelecionaVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSelecionaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEfetuarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(cbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelecionaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblVenderVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVenderVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionaVeiculo)
                    .addComponent(cbTipoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionaVendedor)
                    .addComponent(btnSelecionaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEfetuarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarVenda;
    private javax.swing.JButton btnEfetuarVenda;
    private javax.swing.JButton btnSelecionaCliente;
    private javax.swing.JButton btnSelecionaVeiculo;
    private javax.swing.JButton btnSelecionaVendedor;
    private javax.swing.JComboBox<String> cbTipoVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblVenderVeiculo;
    private javax.swing.JTextArea txtaClienteSelecionado;
    private javax.swing.JTextArea txtaVeiculoSelecionado;
    private javax.swing.JTextArea txtaVendedorSelecionado;
    // End of variables declaration//GEN-END:variables
}
