/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.lojaveiculo.view;

import br.com.lojaveiculo.abstractview.TelaBaseView;
import br.com.lojaveiculo.model.Venda;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author Matheus
 */
public final class EmissaoRelatorioView extends TelaBaseView {

    /**
     * Creates new form RelatorioView
     */
    public EmissaoRelatorioView() {
        initComponents();
        organizaLayout();
    }
    
    @Override
    public void organizaLayout() {
        setContentPane(pblFundo);
        setSize(800, 700);
        setLocationRelativeTo(null);
    }
    
    public void adicionaAcaoAoBotaoEmitir(ActionListener acao){
        btnEmitirRelatorio.addActionListener(acao);
    }
    
    public void adicionaAcaoAoBotaoLimpar(ActionListener acao){
        btnLimpar.addActionListener(acao);
    }
    
    public void imprimeDados(List<Venda> vendas){
        for (Venda v : vendas) {
            txtDados.append("ID Venda: " + v.getIdVenda() + "\n");
            txtDados.append("Nome do Vendedor: " + v.getVendedor().getNome() + "\n");
            txtDados.append("Cliente: " + v.getCliente().getNome() + "\n");
            txtDados.append("CPF do Cliente: " + v.getCliente().getCpf() + "\n");
            txtDados.append("Modeo do Veiculo: " + v.getVeiculo().getModelo() + "\n");
            txtDados.append("Placa do Veiculo: " + v.getVeiculo().getPlaca() + "\n");
            txtDados.append("Valor da venda: R$" + v.getVeiculo().getPreco() + "\n");
            txtDados.append("----------------" + "\n");
        }
        txtDados.append("Quantidade de Vendas: " + vendas.stream().count());
    }
    
    public void limparDadosEmitidos(){
        this.txtDados.setText(null);
    }
    
    public int getTipoRelatorioSelecionado(){
        return cbOrdenacao.getSelectedIndex();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pblFundo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDados = new javax.swing.JTextArea();
        lblOrdenacao = new javax.swing.JLabel();
        cbOrdenacao = new javax.swing.JComboBox<>();
        btnEmitirRelatorio = new javax.swing.JButton();
        btnLimpar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios");

        txtDados.setColumns(20);
        txtDados.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtDados.setForeground(new java.awt.Color(255, 255, 255));
        txtDados.setRows(5);
        jScrollPane1.setViewportView(txtDados);

        lblOrdenacao.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblOrdenacao.setForeground(new java.awt.Color(255, 255, 255));
        lblOrdenacao.setText("Ordenação:");

        cbOrdenacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome do Cliente", "Vendedor", "Placa", "Modelo Veículo", "Preço" }));

        btnEmitirRelatorio.setBackground(new java.awt.Color(82, 148, 226));
        btnEmitirRelatorio.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEmitirRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnEmitirRelatorio.setText("Emitir");

        btnLimpar.setText("Limpar");

        javax.swing.GroupLayout pblFundoLayout = new javax.swing.GroupLayout(pblFundo);
        pblFundo.setLayout(pblFundoLayout);
        pblFundoLayout.setHorizontalGroup(
            pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(pblFundoLayout.createSequentialGroup()
                        .addGroup(pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrdenacao)
                            .addComponent(cbOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnEmitirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pblFundoLayout.setVerticalGroup(
            pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblFundoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pblFundoLayout.createSequentialGroup()
                        .addComponent(lblOrdenacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEmitirRelatorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmitirRelatorio;
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.JComboBox<String> cbOrdenacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrdenacao;
    private javax.swing.JPanel pblFundo;
    private javax.swing.JTextArea txtDados;
    // End of variables declaration//GEN-END:variables

}
