/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.lojaveiculo.view;

import br.com.lojaveiculo.model.Veiculo;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatArcDarkIJTheme;
/**
 *
 * @author Matheus
 */
public class PrincipalView extends javax.swing.JFrame {

    private Veiculo veiculo;
    /**
     * Creates new form InicialView
     */
    public PrincipalView() {
        initComponents();
        
        // Adicionar o painel ao centro do frame
        this.setContentPane(dkpnlFundo);
        this.setSize(500, 400);
        
        // Setar posicao do frame na tela (null = centro)
        this.setLocationRelativeTo(null);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkpnlFundo = new javax.swing.JDesktopPane();
        mbMenuPrincipal = new javax.swing.JMenuBar();
        muCadFuncionarios = new javax.swing.JMenu();
        miCadFuncionarios = new javax.swing.JMenuItem();
        miCadClientes = new javax.swing.JMenuItem();
        miCadVeiculos = new javax.swing.JMenuItem();
        miCadVendas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        muConsultaFuncionarios = new javax.swing.JMenuItem();
        Venda = new javax.swing.JMenu();
        muTelaVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DestkopMotors");
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 900));

        dkpnlFundo.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        javax.swing.GroupLayout dkpnlFundoLayout = new javax.swing.GroupLayout(dkpnlFundo);
        dkpnlFundo.setLayout(dkpnlFundoLayout);
        dkpnlFundoLayout.setHorizontalGroup(
            dkpnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 921, Short.MAX_VALUE)
        );
        dkpnlFundoLayout.setVerticalGroup(
            dkpnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        muCadFuncionarios.setText("Cadastros");

        miCadFuncionarios.setText("Funcionários");
        miCadFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadFuncionariosActionPerformed(evt);
            }
        });
        muCadFuncionarios.add(miCadFuncionarios);

        miCadClientes.setText("Clientes");
        muCadFuncionarios.add(miCadClientes);

        miCadVeiculos.setText("Veículos");
        muCadFuncionarios.add(miCadVeiculos);

        miCadVendas.setText("Vendas");
        muCadFuncionarios.add(miCadVendas);

        mbMenuPrincipal.add(muCadFuncionarios);

        jMenu1.setText("Consultas");

        muConsultaFuncionarios.setText("Funcionarios");
        muConsultaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muConsultaFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(muConsultaFuncionarios);

        mbMenuPrincipal.add(jMenu1);

        Venda.setText("Venda");

        muTelaVenda.setText("Tela Venda");
        muTelaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muTelaVendaActionPerformed(evt);
            }
        });
        Venda.add(muTelaVenda);

        mbMenuPrincipal.add(Venda);

        setJMenuBar(mbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dkpnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dkpnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miCadFuncionariosActionPerformed

    private void muConsultaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muConsultaFuncionariosActionPerformed
       ConsultaFuncionariosView consultaFuncionarios = new ConsultaFuncionariosView();
       consultaFuncionarios.setVisible(true);
    }//GEN-LAST:event_muConsultaFuncionariosActionPerformed

    private void muTelaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muTelaVendaActionPerformed
      VendaView vendaView = new VendaView();
      vendaView.setVisible(true);
    }//GEN-LAST:event_muTelaVendaActionPerformed
    
        public static void main(String args[]) {
            
            FlatArcDarkIJTheme.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PrincipalView().setVisible(true);
            });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Venda;
    private javax.swing.JDesktopPane dkpnlFundo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar mbMenuPrincipal;
    private javax.swing.JMenuItem miCadClientes;
    private javax.swing.JMenuItem miCadFuncionarios;
    private javax.swing.JMenuItem miCadVeiculos;
    private javax.swing.JMenuItem miCadVendas;
    private javax.swing.JMenu muCadFuncionarios;
    private javax.swing.JMenuItem muConsultaFuncionarios;
    private javax.swing.JMenuItem muTelaVenda;
    // End of variables declaration//GEN-END:variables

    
}


