/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.lojaveiculo.view;

import br.com.lojaveiculo.dao.VendaDAO;
import br.com.lojaveiculo.model.Venda;
import br.com.lojaveiculo.repositorio.VendaRepositorio;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author Matheus
 */
public class RelatorioView extends javax.swing.JFrame {

    private final VendaRepositorio RepositorioDeVendas;
    private static List<Venda> vendas = new ArrayList<>();

    /**
     * Creates new form RelatorioView
     */
    public RelatorioView() {
        initComponents();
        setContentPane(pblFundo);
        setSize(800, 700);
        setLocationRelativeTo(null);
        RepositorioDeVendas = new VendaDAO();
        vendas = RepositorioDeVendas.getVenda();
    }
    
    
    public void ordenaPorVendedor(){
        txtDados.setText("");
        Collections.sort(vendas, new Comparator<Venda>() {
            @Override
            public int compare(Venda v1, Venda v2) {
                return v1.getVendedor().getNome().compareTo(v2.getVendedor().getNome());
            }
        });        
    }
    
    public void ordenaPorNomeCliente(){
        txtDados.setText("");
        Collections.sort(vendas, new Comparator<Venda>(){
            @Override
            public int compare(Venda v1, Venda v2){
                return v1.getCliente().getNome().compareTo(v2.getCliente().getNome());
            }
        });
    }
    
    public void ordenaPorPlaca(){
        txtDados.setText("");
        Collections.sort(vendas, new Comparator<Venda>(){
            @Override
            public int compare(Venda v1, Venda v2){
                return v1.getVeiculo().getPlaca().compareTo(v2.getVeiculo().getPlaca());
            }
        });
    }
    
    public void ordenaPorModelo(){
        txtDados.setText("");
        Collections.sort(vendas, new Comparator<Venda>(){
            @Override
            public int compare(Venda v1, Venda v2){
                return v1.getVeiculo().getModelo().compareTo(v2.getVeiculo().getModelo());
            }
        });
    }

    public void ordenaPorPreco(){
        txtDados.setText("");
        RepositorioDeVendas.ordenaPreco();
        vendas = RepositorioDeVendas.getVenda();
    }
    
    public void imprimeDados(){
        for (Venda v : RepositorioDeVendas.getVenda()) {
            txtDados.append("ID Venda: " + v.getIdVenda() + "\n");
            txtDados.append("Nome do Vendedor: " + v.getVendedor().getNome() + "\n");
            txtDados.append("Cliente: " + v.getCliente().getNome() + "\n");
            txtDados.append("CPF do Cliente: " + v.getCliente().getCpf() + "\n");
            txtDados.append("Modeo do Veiculo: " + v.getVeiculo().getModelo() + "\n");
            txtDados.append("Placa do Veiculo: " + v.getVeiculo().getPlaca() + "\n");
            txtDados.append("Valor da venda: R$" + v.getVeiculo().getPreco() + "\n");
            txtDados.append("----------------" + "\n");
        }
        txtDados.append("Quantidade de Vendas: " + vendas.stream().count());
    }
    
    public void chamaOrdenacao(){
        switch(cbOrdenacao.getSelectedIndex()){
            case 0 -> {
                ordenaPorNomeCliente();
                imprimeDados();
            }
            case 1 -> {
                ordenaPorVendedor();
                imprimeDados();
            }
            case 2 -> {
                ordenaPorPlaca();
                imprimeDados();
            }
            case 3 -> {
                ordenaPorModelo();
                imprimeDados();
            }
            case 4 -> {
                ordenaPorPreco();
                imprimeDados();
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pblFundo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDados = new javax.swing.JTextArea();
        lblOrdenacao = new javax.swing.JLabel();
        cbOrdenacao = new javax.swing.JComboBox<>();
        btnEmitirRelatorio = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios");

        txtDados.setColumns(20);
        txtDados.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtDados.setForeground(new java.awt.Color(255, 255, 255));
        txtDados.setRows(5);
        jScrollPane1.setViewportView(txtDados);

        lblOrdenacao.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblOrdenacao.setForeground(new java.awt.Color(255, 255, 255));
        lblOrdenacao.setText("Ordenação:");

        cbOrdenacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome do Cliente", "Vendedor", "Placa", "Modelo Veículo", "Preço" }));

        btnEmitirRelatorio.setBackground(new java.awt.Color(82, 148, 226));
        btnEmitirRelatorio.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEmitirRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnEmitirRelatorio.setText("Emitir");
        btnEmitirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirRelatorioActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Limpar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pblFundoLayout = new javax.swing.GroupLayout(pblFundo);
        pblFundo.setLayout(pblFundoLayout);
        pblFundoLayout.setHorizontalGroup(
            pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(pblFundoLayout.createSequentialGroup()
                        .addGroup(pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrdenacao)
                            .addComponent(cbOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnEmitirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pblFundoLayout.setVerticalGroup(
            pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblFundoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pblFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pblFundoLayout.createSequentialGroup()
                        .addComponent(lblOrdenacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbOrdenacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEmitirRelatorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pblFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmitirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirRelatorioActionPerformed
        chamaOrdenacao();
    }//GEN-LAST:event_btnEmitirRelatorioActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.txtDados.setText("");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmitirRelatorio;
    private javax.swing.JComboBox<String> cbOrdenacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblOrdenacao;
    private javax.swing.JPanel pblFundo;
    private javax.swing.JTextArea txtDados;
    // End of variables declaration//GEN-END:variables
}
